Fixes configf.h for newer versions of the C++ standard library.
  Changes to the C++ standard library for newer versions of gcc leads to
  the following istream related build error:
    error: ‘std::basic_istream<char>’ is an inaccessible base of ‘Configf’
    decltype(__check(declval<typename remove_reference<_Tp>::type*>()));

  This is tied to the 'protected' inheritance of std::ifstream in the
  declaration of Configf. Changing the inheritance to 'public' resolves
  the issue.